### ISSUE TITLE
install jenkins

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/be01-101#52]
- https://www.jenkins.io/doc/book/installing/war-file/

**Comment by parc02** [comment]
## STEP 1
-copy link
![image](https://github.com/beyond-sw-camp/be01-101/assets/148880521/de1fa144-45e0-4ea4-bea3-9541d6187390)

- ~/app/jenkins/
```
$ wget (copy URL)
```

**Comment by Seull1** [comment]
- [시간동기화](https://inpa.tistory.com/entry/LINUX-%F0%9F%93%9A-NTP-%EC%8B%9C%EA%B0%84-%EB%8F%99%EA%B8%B0%ED%99%94-%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-Ubuntu)


![image](https://github.com/beyond-sw-camp/be01-101/assets/148920003/5875c3a0-9e2f-4f76-8b60-d3296b1c328d)

2024-02-22 08:24:11.177+0000 [id=89]    SEVERE  h.model.UpdateCenter$DownloadJob#run: Failed to install plain-credentials
java.security.cert.CertificateNotYetValidException: NotBefore: Fri Feb 23 00:43:30 KST 2024
        at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:273)
        at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:669)
        at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
        at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
Caused: java.security.cert.CertPathValidatorException: validity check failed
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
Caused: sun.security.validator.ValidatorException: PKIX path validation failed
        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
Caused: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:360)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:298)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1511)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:201)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2815)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2727)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1323)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/plain-credentials/143.v1b_df8b_d3b_e48/plain-credentials.hpi to /home/seull/.jenkins/plugins/plain-credentials.jpi.tmp
        at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1334)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/plain-credentials/143.v1b_df8b_d3b_e48/plain-credentials.hpi (redirected to: https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/plain-credentials/143.v1b_df8b_d3b_e48/plain-credentials.hpi)
        at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1368)
        at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1925)
        at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2237)
        at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1899)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by pySatellite** [comment]
## github 토큰
- ✅Settings -> Developer settings -> Personal access tokens -> Tokens (classic)

![image](https://github.com/beyond-sw-camp/be01-101/assets/87309910/e4620d55-7804-4f5b-9ef8-8711e90c58a7)

**Comment by parc02** [comment]
## FYI
![image](https://github.com/beyond-sw-camp/be01-101/assets/148880521/3ab5026c-021f-495a-8d40-0dd9d41477f7)
JAVA11은 2024년 9월 30일까지만 지원한다고 합니다

**Comment by jsmin6330** [comment]
민성님꺼 오류 메시지 해석 


이 오류 메시지는 Jenkins 플러그인 설치 중에 발생한 문제를 설명하고 있습니다. 구체적으로는 plain-credentials 플러그인을 설치하려고 시도할 때 발생한 오류입니다. 오류의 핵심 원인은 다음과 같습니다:

인증서 유효성 검사 실패: 설치 과정에서 사용된 인증서가 아직 유효하지 않음을 나타냅니다. 오류 메시지에서 java.security.cert.CertificateNotYetValidException: NotBefore: Fri Feb 23 00:43:30 KST 2024라는 부분은 인증서가 2024년 2월 23일 00시 43분 30초부터 유효하다는 것을 의미합니다. 하지만 이 작업이 시도된 시간은 그보다 이르기 때문에 인증서가 아직 유효하지 않다는 오류가 발생한 것입니다.

SSL 핸드셰이크 실패: javax.net.ssl.SSLHandshakeException 오류는 SSL 핸드셰이크 과정에서 인증서 유효성 검사 실패로 인해 발생합니다. 이는 보안 연결을 설정할 때 서버의 인증서가 클라이언트에 의해 신뢰될 수 없거나 문제가 있을 때 나타날 수 있습니다.

다운로드 실패: 최종적으로, 이 문제로 인해 Jenkins는 plain-credentials 플러그인을 다운로드할 수 없었습니다. 오류 메시지에서는 Failed to load https://updates.jenkins.io/download/plugins/plain-credentials/143.v1b_df8b_d3b_e48/plain-credentials.hpi와 같이 특정 URL에서 플러그인을 다운로드하는 데 실패했음을 나타냅니다.

해결 방법으로는 시스템 시간을 확인하여 정확한 시간으로 설정하는 것이 중요합니다. 또한, 인증서가 유효한 기간 내에 있는지 확인해야 합니다. 문제가 지속되면 Jenkins 업데이트 사이트의 인증서 상태를 확인하거나 다른 미러 사이트를 사용해 볼 수 있습니다.

**Comment by jsmin6330** [comment]
2. 수동으로 시간 설정하기
시간 동기화에 문제가 있다면, WSL 내에서 시간을 수동으로 설정할 수 있습니다.

현재 시간대 확인: 우선, 현재 설정된 시간대를 확인합니다. WSL 터미널에서 다음 명령어를 실행합니다.
`timedatectl`
이 명령어는 현재 시간대와 시간 동기화 상태를 보여줍니다.

시간대 설정: 시간대를 변경하려면, timedatectl 명령어를 사용합니다. 예를 들어, 서울 시간대로 설정하려면 다음과 같이 실행합니다.
`sudo timedatectl set-timezone Asia/Seoul`
이 명령어는 시스템의 시간대를 변경합니다. 변경할 시간대의 정확한 이름은 timedatectl list-timezones 명령어로 확인할 수 있습니다.

날짜와 시간 수동 설정: 특정 날짜와 시간으로 설정하고 싶다면, date 명령어를 사용하여 수동으로 설정할 수 있습니다. 예를 들어, 2024년 2월 26일 15시 30분으로 설정하려면 다음과 같이 실행합니다.
`sudo date --set="2024-02-26 15:30:00"`

이 명령어는 시스템의 날짜와 시간을 직접 설정합니다.
